name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install selene
        run: |
          wget -qO- https://github.com/Kampfkarren/selene/releases/latest/download/selene-linux.zip | busybox unzip -
          chmod +x ./selene
          sudo mv ./selene /usr/local/bin/

      - name: Run selene
        run: selene lua/

      - name: Install stylua
        run: |
          wget -qO- https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux.zip | busybox unzip -
          chmod +x ./stylua
          sudo mv ./stylua /usr/local/bin/

      - name: Check formatting
        run: stylua --check lua/ colors/

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Run tests
        run: |
          nvim --version
          nvim --headless -u tests/init.lua +qa

      - name: Check theme loads
        run: |
          nvim --headless -c "set rtp+=$(pwd)" -c "colorscheme lilac" -c "qa" || exit 1

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Lint markdown files
        run: markdownlint '**/*.md' --ignore node_modules

      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
          config-file: '.github/markdown-link-check.json'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Generate compiled theme
        run: |
          nvim --headless -u scripts/compile.lua +qa

      - name: Validate color palette
        run: |
          python3 scripts/validate_colors.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-theme
          path: |
            cache/lilac_compiled.lua
            extras/
